name: Deploy Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Firebase Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Firebase Deploy
        run: firebase deploy --token "$FIREBASE_TOKEN" --project imtihan-uygulamasi

